### PR TITLE
Automated backups and minor improvements

### LINKED ISSUE #109: add automatic backup
use `https://django-dbbackup.readthedocs.io/en/stable/` and ensure we do have
- backup to dropbox
- on deploy
- daily at night (swiss timezone)
- encrypted
  explore the lib and add what you consider useful. document this.

please also provide instructions for prod setup

ensure it will raise errors with confs are missing

see deploy script for on deploy backups

### PR DESCRIPTION
**Pull request by msamoylov**
-  Added missing instructions for setting `RAVEN_DSN` and `RAVEN_DSN_PUBLIC` in dev copies
- Introduced `.editorconfig`
- Fixes #109: introducing automated backups

I would recommend storing backups at Amazon S3 at a configured bucket. Read more about that technique at https://samoylov.tech/2016/07/09/storing-ghost-backups-at-amazon-s3/

### CODE REVIEW

**Comment by patroqueeet** [comment]
Dear,

please resolve conflicts (pull latest develop branch and merge). then this wont be sufficient then. where inside the dopbox wil the files be stored? secondly we need to have the backup done on before any deploy (see `deploy.sh`) and also nightly builds (swiss timezone). furthermore what options are recommended to use to make storage usage low and security high?

finally we need to backup not only db but also existing user files. please provide a solution!

what else did we miss, so we will have a perfect backup in place?

**Comment by patroqueeet** [comment]
looks like you also missed updating the deps files

**Comment by msamoylov** [comment]
@patroqueeet there were no conflicts at the moment of creating this PR. Anyways, this is fixed now.

For some reason I sent you a partial commit yesterday. No idea why.

**Comment by msamoylov** [comment]
@patroqueeet please note https://github.com/msamoylov/darg/blob/55579c0dc3db01d1cec857b72919a7b231346cdf/deploy.sh#L7

We create backups before running database migrations or really doing anything. 

Nightly backups feature is described in https://raw.githubusercontent.com/msamoylov/darg/55579c0dc3db01d1cec857b72919a7b231346cdf/docs/backups.rst

**Comment by patroqueeet** [comment]
Dear, for cron we rely on django celery DB backend / PeriodicTasks. Mind adding this very small one using `call_command` and we're done...

**Comment by msamoylov** [comment]
@patroqueeet I'm not seeing any examples of handling periodic tasks in your project. Can you please demonstrate it?

**Comment by patroqueeet** [comment]
I personally like stuff like that: https://gist.github.com/patroqueeet/096d8ec72cb7fec29492cd8fb61395e2 (requires django-celery DatabaseBackend)

**Comment by msamoylov** [comment]
Hi @patroqueeet. Please review the updated PR and https://github.com/patroqueeet/darg/pull/111/commits/ff082da9456b8e60546aae7f5bd4fd53b28bd3f5

**Comment by patroqueeet** [comment]
Dear,

did you test it? 
```
(.ve) Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/runner/aktienregister/.ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/runner/aktienregister/.ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/home/runner/aktienregister/.ve/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/runner/aktienregister/.ve/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/runner/aktienregister/.ve/local/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/runner/aktienregister/site/project/__init__.py", line 5, in <module>
    from .celery import app as celery_app  # noqa
  File "/home/runner/aktienregister/site/project/celery.py", line 38, in <module>
    @app.on_after_configure.connect
AttributeError: 'Celery' object has no attribute 'on_after_configure'
```

github shows you when builds are failing....

screenshot 2016-11-13 08 55 36

 I recommend to add an test to the repo, so we can guarantee that this is and will stay working in the future.

**Comment by msamoylov** [comment]
@patroqueeet that was caused by the outdated Celery. My bad, I forgot to include the latest stable version.

**Pull request closed without merging**
